/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpgc.rpg126763;

import it.unicam.cs.mpgc.rpg126763.models.Equip;
import it.unicam.cs.mpgc.rpg126763.models.Personaggio;

public class App {

    public static void main(String[] args) {

        Personaggio test = new Personaggio("Linden");
        System.out.println(test);
        test.setWeapon(Equip.SWORD);
        System.out.println(test);
    }
}
